"""create events table

Revision ID: b56aaea891ed
Revises: d531df6dc632
Create Date: 2026-07-23 19:23:22.779920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56aaea891ed'
down_revision: Union[str, Sequence[str], None] = 'd531df6dc632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('is_all_day', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='America/New_York', nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('event_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'cancelled', 'inactive')", name=op.f('ck_events_status')),
    sa.CheckConstraint('ends_at IS NULL OR ends_at >= starts_at', name=op.f('ck_events_end_after_start')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_events_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_events_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_department_id'), 'events', ['department_id'], unique=False)
    op.create_index('ix_events_org_department_status_start', 'events', ['organization_id', 'department_id', 'status', 'starts_at'], unique=False)
    op.create_index(op.f('ix_events_organization_id'), 'events', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_organization_id'), table_name='events')
    op.drop_index('ix_events_org_department_status_start', table_name='events')
    op.drop_index(op.f('ix_events_department_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
