"""create resources table

Revision ID: d1234767c01a
Revises: 33ac84be3d0e
Create Date: 2026-08-01 01:17:50.838672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1234767c01a'
down_revision: Union[str, Sequence[str], None] = '33ac84be3d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('aliases_json', sa.JSON(), nullable=True),
    sa.Column('topics_json', sa.JSON(), nullable=True),
    sa.Column('when_to_use', sa.Text(), nullable=True),
    sa.Column('when_not_to_use', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("resource_type IN ('document', 'external_link', 'form', 'guide', 'website', 'information')", name=op.f('ck_resources_resource_type')),
    sa.CheckConstraint("status IN ('draft', 'published', 'inactive')", name=op.f('ck_resources_status')),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_resources_display_order_nonnegative')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_resources_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_resources_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_resources_organization_id'))
    )
    op.create_index(op.f('ix_resources_department_id'), 'resources', ['department_id'], unique=False)
    op.create_index('ix_resources_org_department_status', 'resources', ['organization_id', 'department_id', 'status'], unique=False)
    op.create_index('ix_resources_org_status_type', 'resources', ['organization_id', 'status', 'resource_type'], unique=False)
    op.create_index(op.f('ix_resources_organization_id'), 'resources', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_organization_id'), table_name='resources')
    op.drop_index('ix_resources_org_status_type', table_name='resources')
    op.drop_index('ix_resources_org_department_status', table_name='resources')
    op.drop_index(op.f('ix_resources_department_id'), table_name='resources')
    op.drop_table('resources')
    # ### end Alembic commands ###
